; CouchDB Configuration Settings

; Custom settings should be made in this file. They will override settings
; in default.ini, but unlike changes made to default.ini, this file won't be
; overwritten on server upgrade.

[couchdb]
database_dir = /data/couchdb
view_index_dir = /data/couchdb
max_document_size = 4294967296 ; bytes
os_process_timeout = 30000
single_node = true


[cluster]
; All data is stored on the single node
n = 1
q = 1

[query_server_config]
; Default limit is 2^28=268435456. Override it to INTEGER.MAX to be in sync with CouchDB 1.x
query_limit = 2147483646

[log]
level = info
writer = file
file = /data/log/couchdb3.log

[admins]
admin = admin
